---
categories:
  Actions:
  - Button
  - Dropdown
  - Fab
  - Filter
  - Modal
  - Swap
  - ThemeController
  Data display:
  - Accordion
  - Avatar
  - Badge
  - Card
  - Carousel
  - Chat
  - Collapse
  - Countdown
  - Diff
  - HoverGallery
  - Kbd
  - List
  - Stat
  - Table
  - Timeline
  Data Input:
  - Calendar
  - Checkbox
  - Fieldset
  - FileInput
  - FormControl
  - Input
  - Label
  - Radio
  - Range
  - Rating
  - Select
  - Textarea
  - Toggle
  - Validator
  Feedback:
  - Alert
  - Loading
  - Progress
  - RadialProgress
  - Skeleton
  - Status
  - Toast
  - Tooltip
  Layout:
  - Divider
  - Drawer
  - Footer
  - Hero
  - Indicator
  - Join
  - Mask
  - Stack
  Mockup:
  - MockupBrowser
  - MockupCode
  - MockupPhone
  - MockupWindow
  Navigation:
  - Breadcrumbs
  - Dock
  - Link
  - Menu
  - Navbar
  - Pagination
  - Steps
  - Tab
